
package org.soa.ws.tp3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopCatalogImplService", targetNamespace = "http://tp3.ws.soa.org/", wsdlLocation = "http://hedia:8080/ShopCatalogWS/ShopCatalogImplService?wsdl")
public class ShopCatalogImplService
    extends Service
{

    private final static URL SHOPCATALOGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPCATALOGIMPLSERVICE_EXCEPTION;
    private final static QName SHOPCATALOGIMPLSERVICE_QNAME = new QName("http://tp3.ws.soa.org/", "ShopCatalogImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hedia:8080/ShopCatalogWS/ShopCatalogImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPCATALOGIMPLSERVICE_WSDL_LOCATION = url;
        SHOPCATALOGIMPLSERVICE_EXCEPTION = e;
    }

    public ShopCatalogImplService() {
        super(__getWsdlLocation(), SHOPCATALOGIMPLSERVICE_QNAME);
    }

    public ShopCatalogImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPCATALOGIMPLSERVICE_QNAME, features);
    }

    public ShopCatalogImplService(URL wsdlLocation) {
        super(wsdlLocation, SHOPCATALOGIMPLSERVICE_QNAME);
    }

    public ShopCatalogImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPCATALOGIMPLSERVICE_QNAME, features);
    }

    public ShopCatalogImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopCatalogImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatalogMagasin
     */
    @WebEndpoint(name = "ShopCatalogImplPort")
    public CatalogMagasin getShopCatalogImplPort() {
        return super.getPort(new QName("http://tp3.ws.soa.org/", "ShopCatalogImplPort"), CatalogMagasin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogMagasin
     */
    @WebEndpoint(name = "ShopCatalogImplPort")
    public CatalogMagasin getShopCatalogImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tp3.ws.soa.org/", "ShopCatalogImplPort"), CatalogMagasin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPCATALOGIMPLSERVICE_EXCEPTION!= null) {
            throw SHOPCATALOGIMPLSERVICE_EXCEPTION;
        }
        return SHOPCATALOGIMPLSERVICE_WSDL_LOCATION;
    }

}
